[package]
name    = "mix_packages"
version = "0.0.0"
edition = "2021"

[dependencies.futures-util]
version = "0.3"

[dependencies.mix_atom]
path = "../atom"

[dependencies.mix_build]
path = "../build"

[dependencies.mix_config]
path = "../config"

[dependencies.mix_env]
path = "../env"

[dependencies.mix_id]
path = "../id"

[dependencies.mix_manifest]
path = "../manifest"

[dependencies.mix_shell]
path = "../shell"

[dependencies.mix_source]
path = "../source"

[dependencies.mix_triple]
path = "../triple"

[dependencies.path]
git = "https://gitdab.com/undefined/path" 

[dependencies.regex]
version = "1.5"

[dependencies.semver]
version = "1.0"
