[package]
name    = "milk_packages"
version = "0.0.0"
edition = "2021"

[dependencies.futures-util]
version = "0.3"

[dependencies.milk_atom]
path = "../atom"

[dependencies.milk_build]
path = "../build"

[dependencies.milk_config]
path = "../config"

[dependencies.milk_env]
path = "../env"

[dependencies.milk_id]
path = "../id"

[dependencies.milk_manifest]
path = "../manifest"

[dependencies.milk_shell]
path = "../shell"

[dependencies.milk_source]
path = "../source"

[dependencies.milk_triple]
path = "../triple"

[dependencies.path]
git = "https://gitdab.com/undefined/path" 

[dependencies.regex]
version = "1.5"

[dependencies.semver]
version = "1.0"
