[package]
name    = "manager"
version = "0.0.0"
authors = ["saraph"]
edition = "2018"

[dependencies]
anyhow        = "*"
bytes         = "*"
byte-unit     = "*"
crossterm     = "*"
futures       = "*"
pico-args     = { version = "*", features = ["eq-separator", "short-space-opt"] }
reqwest       = { version = "*", features = ["brotli", "gzip", "json", "rustls-tls", "stream"], default-features = false }
semver        = { version = "*", features = ["serde"] }
semver-parser = "*"
serde         = { version = "*", features = ["derive"] }
serde_json    = "*"
serde_yaml    = "*"
tokio         = { version = "*", features = ["full"] }
tokio-stream  = { version = "*", features = ["fs"] }
ufmt          = { features = ["std"], git = "https://github.com/saraph/ufmt" }
url           = { version = "*", features = ["serde"] }
