[package]
name    = "candy"
version = "0.0.0"
authors = ["kalmari"]
edition = "2018"

[dependencies]
anyhow = "1.0"
crossterm = "0.18"
nix = "0.19"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
tokio = { version = "0.3", features = ["macros", "process", "rt-multi-thread"] }
toml = "0.5"
