[package]
name    = "mochi"
version = "0.0.1"
authors = ["dysmal"]
edition = "2018"

[dependencies]
anyhow        = "1.0"
bytes         = "1.0"
byte-unit     = "4.0"
clap          = "3.0.0-beta"
crossterm     = "0.19"
futures       = "0.3"
git2          = "0.13"
multimap      = "0.8"
openssl       = { version = "0.10", features = ["vendored"] }
reqwest       = { version = "0.11", features = ["brotli", "gzip", "json", "rustls-tls", "stream"], default-features = false }
semver        = { version = "0.11", features = ["serde"] }
semver-parser = "0.10"
serde         = { version = "1.0", features = ["derive"] }
serde_json    = "1.0"
serde_yaml    = "0.8"
tokio         = { version = "1.0", features = ["full"] }
tokio-stream  = { version = "0.1", features = ["fs"] }
