[package]
name    = "mix_version"
version = "0.0.0"
edition = "2021"

[dependencies.mix_shell]
path = "../shell"

[dependencies.path]
git = "https://gitdab.com/undefined/path"

[dependencies.semver]
version = "1.0"

[dependencies.serde]
optional = true
version = "1.0"
