[package]
name    = "milk_metadata"
version = "0.0.0"
edition = "2021"

[dependencies.milk_id]
path = "../id"

[dependencies.milk_triple]
path = "../triple"

[dependencies.path]
git = "https://gitdab.com/undefined/path"

[dependencies.regex]
version = "1.5"

[dependencies.semver]
version = "1.0"

